# Use root/example as user/password credentials
version: '3.1'

services:
  # api:
  #   build: .
  #   container_name: blog-app
  #   ports: 
  #    - 3001:3001
  #   command: "npm start"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH: false
